[package]
name = "relconf"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde-toml-merge = "0.3.8"
serde_yaml = "0.9.34"
shellexpand = { version = "3.1.0", features = ["path"] }
toml = "0.8.14"
